plugins {
    id 'com.android.application'
}

android {
    namespace 'com.touchdeveloper.app'
    compileSdk 34

    defaultConfig {
        applicationId "com.touchdeveloper.app"
        minSdk 26
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        buildConfig true
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
